using System;
using System.Collections.Generic;
using System.Linq;

public class Questions
{
    public string Id { get; set; }
    public string Category { get; set; } // Transport, Housing, Environment, Safety, and Tech
    public string Prompt { get; set; }
    public List<string> Choices { get; set; }
    public string CorrectAnswer { get; set; }
    public string Hint { get; set; }
}

public static class QuestionsBank
{
    public const string PromptPrefix = "The city is changing. What would you do in the following case?";

    /// Used Gen AI to help generate prompts and hints
    public static List<Questions> AllQuestions = new List<Questions>
    {
        new Questions{ Id="Q01", Category="Transport", Prompt="Chief, our city has earned some extra budget. Where should we invest it in?", Choices=new List<string>{"A) Highways","B) Public Transit","C) Parking"}, CorrectAnswer="B", Hint="Public transit moves more people per dollar than highways and reduces traffic congestion."},
        new Questions{ Id="Q02", Category="Transport", Prompt="Chief, our roads are gettng filled with traffic. What should we do?", Choices=new List<string>{"A) Add lanes","B) Improve buses","C) Ignore"}, CorrectAnswer="B", Hint="Better buses reduce the number of cars on the road, addressing the root cause of traffic."},
        new Questions{ Id="Q03", Category="Transport", Prompt="Chief, parents are complaining about unsafe school roads. What should we do?", Choices=new List<string>{"A) Crosswalks","B) Parking","C) Nothing"}, CorrectAnswer="A", Hint="Crosswalks and pedestrian signals are proven to reduce accidents near schools."},
        new Questions{ Id="Q04", Category="Housing", Prompt="Chief, housing demand is growing. How should we address this?", Choices=new List<string>{"A) Affordable units","B) Luxury only","C) Stop builds"}, CorrectAnswer="A", Hint="Affordable housing ensures all residents can live in the city, not just the wealthy."},
        new Questions{ Id="Q05", Category="Housing", Prompt="Chief, we have some old unsafe buildings downtown. What should we do with them?", Choices=new List<string>{"A) Renovate","B) Demolish all","C) Leave it"}, CorrectAnswer="A", Hint="Renovating preserves housing stock and community history while improving safety."},
        new Questions{ Id="Q06", Category="Environment", Prompt="Chief, we have some extra space in the west. What should we build on it?", Choices=new List<string>{"A) Parks","B) Malls","C) Factories"}, CorrectAnswer="A", Hint="Parks improve mental health, reduce urban heat, and provide community gathering spaces."},
        new Questions{ Id="Q07", Category="Environment", Prompt="Chief, our waste management reports waste overflow. How should we address this?", Choices=new List<string>{"A) Recycling","B) Bigger landfill","C) Ignore"}, CorrectAnswer="A", Hint="Recycling reduces landfill use and conserves natural resources for future generations."},
        new Questions{ Id="Q08", Category="Environment", Prompt="Chief, our waste management reports higher plastic waste in the last year. Should we do something about this?", Choices=new List<string>{"A) Ban plastics","B) Promote plastic","C) No change"}, CorrectAnswer="A", Hint="Banning single-use plastics significantly reduces pollution in waterways and oceans."},
        new Questions{ Id="Q09", Category="Safety", Prompt="Chief, the people are feeling unsafe walking around at night. How can we ensure their safety?", Choices=new List<string>{"A) Lighting","B) Close parks","C) Ignore"}, CorrectAnswer="A", Hint="Well-lit streets deter crime and make residents feel safer without restricting access."},
        new Questions{ Id="Q10", Category="Tech", Prompt="Chief, what is our plan in the event of a disaster?", Choices=new List<string>{"A) Warning systems","B) Stockpile resources","C) Wait"}, CorrectAnswer="A", Hint="Early warning systems save lives by giving residents time to evacuate or take shelter."},
        new Questions{ Id="Q11", Category="Transport", Prompt="Chief, there's been an increase in bike accidents in the past three months. What should we do?", Choices=new List<string>{"A) Bike lanes","B) Ban bikes","C) Signs only"}, CorrectAnswer="A", Hint="Dedicated bike lanes physically separate cyclists from traffic, dramatically reducing accidents."},
        new Questions{ Id="Q12", Category="Housing", Prompt="Chief, the people are upset about the limited downtown space. What should we do?", Choices=new List<string>{"A) Mixed use","B) Parking towers","C) Empty"}, CorrectAnswer="A", Hint="Mixed-use buildings combine residential and commercial space, maximizing limited urban land."},
        new Questions{ Id="Q13", Category="Safety", Prompt="Chief, we've been getting complaints about the lack of access for disabled people. How should we address this?", Choices=new List<string>{"A) Ramps","B) No change","C) Stairs"}, CorrectAnswer="A", Hint="Ramps and accessible design allow all residents to participate equally in city life."},
        new Questions{ Id="Q14", Category="Tech", Prompt="Chief, the people don't feel as if they are being listened to. What should we do?", Choices=new List<string>{"A) Town halls","B) Close meetings","C) Ignore"}, CorrectAnswer="A", Hint="Town halls give residents a voice in decisions that affect their community."},
        new Questions{ Id="Q15", Category="Environment", Prompt="Chief, the people are asking for more decoration around the city.", Choices=new List<string>{"A) Urban forest","B) Statues","C) Billboards"}, CorrectAnswer="A", Hint="Urban forests improve air quality, reduce heat, and boost biodiversity in cities."},
        new Questions{ Id="Q16", Category="Health", Prompt="Chief, a recent survey suggests public health is declining. What should we do about this?", Choices=new List<string>{"A) Free clinics","B) Close hospitals","C) Ignore"}, CorrectAnswer="A", Hint="Free clinics provide early intervention, preventing costly emergency care later."},
        new Questions{ Id="Q17", Category="Transport", Prompt="Chief, we've been recording higher air pollution than last year. What should we do?", Choices=new List<string>{"A) Car-free days","B) Cheap gas","C) Ignore"}, CorrectAnswer="A", Hint="Car-free days reduce emissions and raise awareness about sustainable transport options."},
        new Questions{ Id="Q18", Category="Transport", Prompt="Chief, it's time to expand our transportation options.", Choices=new List<string>{"A) Bike lanes","B) Car roads","C) Helipads"}, CorrectAnswer="A", Hint="Bike infrastructure is cost-effective and encourages healthy, emission-free commuting."},
        new Questions{ Id="Q19", Category="Transport", Prompt="Chief, the people are unhappy about the cost of public transportation. What should we do?", Choices=new List<string>{"A) Subsidize","B) Raise fares","C) Lower quality"}, CorrectAnswer="A", Hint="Subsidizing transit keeps it accessible for low-income residents who depend on it most."},
        new Questions{ Id="Q20", Category="Transport", Prompt="Chief, we've recorded higher carbon emissions in the last year. What should we do?", Choices=new List<string>{"A) EV incentives","B) Diesel promo","C) Ignore"}, CorrectAnswer="A", Hint="EV incentives accelerate the transition away from fossil fuels and reduce city emissions."},
        new Questions{ Id="Q21", Category="Transport", Prompt="Chief, our recent survey reports commuting times are getting longer. How should we address this?", Choices=new List<string>{"A) Remote work","B) Longer hours","C) Close offices"}, CorrectAnswer="A", Hint="Remote work reduces peak-hour congestion and improves work-life balance for residents."},
        new Questions{ Id="Q22", Category="Housing", Prompt="Chief, our city streets are overcrowded! The people need more housing.", Choices=new List<string>{"A) Dense housing","B) Endless suburbs","C) Stop permits"}, CorrectAnswer="A", Hint="Dense housing reduces sprawl, preserves green space, and makes public transit more viable."},
        new Questions{ Id="Q23", Category="Housing", Prompt="Chief, rent prices are out of control! What should we do?", Choices=new List<string>{"A) Rent control","B) Remove rules","C) Ignore"}, CorrectAnswer="A", Hint="Rent control protects existing residents from being priced out of their neighbourhoods."},
        new Questions{ Id="Q24", Category="Housing", Prompt="Chief, we've recently acquired new land in the south. What should we build on it?", Choices=new List<string>{"A) Community garden","B) Factory","C) Fence"}, CorrectAnswer="A", Hint="Community gardens provide fresh food, green space, and bring neighbours together."},
        new Questions{ Id="Q25", Category="Environment", Prompt="Chief, there is an increase in heat waves. What should we do?", Choices=new List<string>{"A) Plant trees","B) Remove green","C) Asphalt"}, CorrectAnswer="A", Hint="Trees provide shade and release moisture, naturally cooling urban areas during heat waves."},
        new Questions{ Id="Q26", Category="Environment", Prompt="Chief, the local river is being polluted. This could be dangerous to our water supply. What should we do about it?", Choices=new List<string>{"A) Enforce fines","B) Allow dumping","C) Close river"}, CorrectAnswer="A", Hint="Fines hold polluters accountable and fund cleanup efforts to restore river ecosystems."},
        new Questions{ Id="Q27", Category="Environment", Prompt="Chief, a study has shown our air quality is dropping at a rapid rate. What should we do?", Choices=new List<string>{"A) Green roofs","B) Coal plants","C) Ignore"}, CorrectAnswer="A", Hint="Green roofs absorb pollutants, reduce runoff, and insulate buildings naturally."},
        new Questions{ Id="Q28", Category="Environment", Prompt="Chief, we need a plan for when a flood will occur.", Choices=new List<string>{"A) Drainage","B) Build wetlands","C) Wait"}, CorrectAnswer="A", Hint="Improved drainage systems redirect excess water quickly, protecting homes and infrastructure."},
        new Questions{ Id="Q29", Category="Safety", Prompt="Chief, there's been a spike in crime recently. Our police force is trying the best they can, but they still need support. What should we do?", Choices=new List<string>{"A) Community policing","B) Curfew only","C) Ignore"}, CorrectAnswer="A", Hint="Community policing builds trust between residents and police, addressing root causes of crime."},
        new Questions{ Id="Q30", Category="Safety", Prompt="Chief, we've received reports about the rise of youth unemployment? How should we address this?", Choices=new List<string>{"A) Skills centers","B) Raise limits","C) Lower standards"}, CorrectAnswer="A", Hint="Skills centers give young people tools to enter the workforce and contribute to the community."},
        new Questions{ Id="Q31", Category="Safety", Prompt="Chief, our recent survey suggests increased loneliness among the elderly. How can we help them?", Choices=new List<string>{"A) Community hubs","B) Reduce services","C) Ignore"}, CorrectAnswer="A", Hint="Community hubs give elderly residents social connection, reducing depression and health decline."},
        new Questions{ Id="Q32", Category="Tech", Prompt="Chief, our energy sector reports a rising demand for energy. We need an alternative power source.", Choices=new List<string>{"A) Solar panels","B) Coal","C) Power cuts"}, CorrectAnswer="A", Hint="Solar panels provide clean renewable energy and reduce long-term electricity costs."},
        new Questions{ Id="Q33", Category="Tech", Prompt="Chief, our new policy has been approved! How should we deliver the news?", Choices=new List<string>{"A) Digital traffic","B) Paper only","C) No change"}, CorrectAnswer="A", Hint="Digital traffic systems reduce congestion in real time by adapting to live road conditions."},
        new Questions{ Id="Q34", Category="Housing", Prompt="Chief, we've been getting reports about the rise of homelessness. How can we solve this?", Choices=new List<string>{"A) Expand shelters","B) Push out","C) Ignore"}, CorrectAnswer="A", Hint="Expanding shelters provides immediate safety and connects people to long-term housing support."},
        new Questions{ Id="Q35", Category="Housing", Prompt="Chief, the slums are growing. The people there need a safer place. What should we do?", Choices=new List<string>{"A) Upgrade infra","B) Evict","C) Ignore"}, CorrectAnswer="A", Hint="Upgrading infrastructure in existing communities is more humane and cost-effective than eviction."},
        new Questions{ Id="Q36", Category="Housing", Prompt="Chief, there's been an increase in noise complaints. Should we do something about this?", Choices=new List<string>{"A) Zoning laws","B) Nightlife everywhere","C) Remove limits"}, CorrectAnswer="A", Hint="Zoning laws separate noisy commercial areas from residential zones, protecting quality of life."},
        new Questions{ Id="Q37", Category="Environment", Prompt="Chief, the people are reporting the absence of wildlife around our city. How should we handle it?", Choices=new List<string>{"A) Protected zones","B) Highways","C) Hunting"}, CorrectAnswer="A", Hint="Protected zones preserve habitat and allow wildlife populations to recover naturally."},
        new Questions{ Id="Q38", Category="Environment", Prompt="Chief, a new private factory has been built and hiring. However, experts say this will add more pollution in our air. What should we do?", Choices=new List<string>{"A) Strict rules","B) Approve","C) Hide data"}, CorrectAnswer="A", Hint="Strict environmental rules allow economic growth while protecting residents health and air quality."},
        new Questions{ Id="Q39", Category="Environment", Prompt="Chief, a drought is expected to occur, which will limit our water supply. What should we do?", Choices=new List<string>{"A) Conserve","B) Wait","C) Use more"}, CorrectAnswer="A", Hint="Conservation measures extend water supply and build resilience against future droughts."},
        new Questions{ Id="Q40", Category="Safety", Prompt="Chief, there have been some incidents at one of our public transport stations. What should we do?", Choices=new List<string>{"A) Safety staff","B) Dismiss","C) Reduce service"}, CorrectAnswer="A", Hint="Dedicated safety staff deter harassment and make transit welcoming for all passengers."},
        new Questions{ Id="Q41", Category="Safety", Prompt="Chief, our recent survey suggests inequality in residential prices between the lower and higher class. What should we do about this?", Choices=new List<string>{"A) Social housing","B) Tax breaks rich","C) Ignore"}, CorrectAnswer="A", Hint="Social housing provides stable homes for low-income residents, reducing inequality at its root."},
        new Questions{ Id="Q42", Category="Tech", Prompt="Chief, a security company has approached us to install surveillance cameras across the city. Any suggestions from you before we approve this?", Choices=new List<string>{"A) Privacy rules","B) No oversight","C) Sell footage"}, CorrectAnswer="A", Hint="Privacy rules ensure surveillance technology is used responsibly and protects civil liberties."},
        new Questions{ Id="Q43", Category="Tech", Prompt="Chief, the people are concerned about their data privacy when they surf the Web. What should we do?", Choices=new List<string>{"A) Strong laws","B) Sell data","C) Ignore"}, CorrectAnswer="A", Hint="Strong data laws protect residents from exploitation and build trust in city digital services."},
        new Questions{ Id="Q44", Category="Tech", Prompt="Chief, the people want transparency on our tax spending. This may potentially reveal sensitive info. How should we answer them?", Choices=new List<string>{"A) Public dashboards","B) Hidden budgets","C) Partial data"}, CorrectAnswer="A", Hint="Public dashboards hold government accountable and help residents understand how taxes are spent."},
        new Questions{ Id="Q45", Category="Tech", Prompt="Chief, there's a growing gap in tech inequality. The people need access to the internet. How do we solve this?", Choices=new List<string>{"A) Free Wi-Fi","B) Paid Wi-Fi","C) Remove internet access"}, CorrectAnswer="A", Hint="Free Wi-Fi ensures all residents can access digital services, education, and job opportunities."},
        new Questions{ Id="Q46", Category="Tech", Prompt="Chief, we've finished our official government website! There is a lot of information available, but should we open it to the public or restrict access?", Choices=new List<string>{"A) Open portal","B) Restrict","C) Delete"}, CorrectAnswer="A", Hint="Open data portals allow researchers and citizens to identify problems and propose solutions."},
        new Questions{ Id="Q47", Category="Tech", Prompt="Chief, our policies are sure to improve the city and keep the people happy. Any plans on how long these will last?", Choices=new List<string>{"A) 20-year plan","B) Short profits","C) No plan"}, CorrectAnswer="A", Hint="Long-term planning ensures the city grows sustainably and prepares for future challenges."},
        new Questions{ Id="Q48", Category="Transport", Prompt="Chief, our transportation services have reported lower income in the past month. They theorize it's because of the low number of people taking public transport. Should we do something about it?", Choices=new List<string>{"A) Improve reliability","B) Cancel","C) Raise fares"}, CorrectAnswer="A", Hint="Reliable transit encourages more people to leave their cars at home, reducing congestion."},
        new Questions{ Id="Q49", Category="Transport", Prompt="Chief, private businesses are demanding more parking lots to serve more customers. Building these parking lots would require the demolition of a local recreational park. What should we do?", Choices=new List<string>{"A) Better transit","B) Replace the park","C) Parking only"}, CorrectAnswer="A", Hint="Better transit serves more people than parking lots and keeps green spaces intact."},
        new Questions{ Id="Q50", Category="Environment", Prompt="Chief, we've been getting reports about a severe heat island effect. How should we address this?", Choices=new List<string>{"A) Green roofs","B) More asphalt","C) Ignore"}, CorrectAnswer="A", Hint="Green roofs reflect heat, insulate buildings, and cool surrounding air naturally."},
    };

    public static List<string> GetShuffledChoices(Questions question, out int correctIndex)
    {
        // Strip the "A) ", "B) ", "C) " prefixes
        var stripped = question.Choices.Select(c => c.Substring(3)).ToList();

        // Remember the correct answer text before shuffling
        string correctText = stripped[question.Choices.FindIndex(c => c.StartsWith(question.CorrectAnswer + ")"))];

        // Shuffle
        var shuffled = stripped.OrderBy(_ => Guid.NewGuid()).ToList();

        // Find where the correct answer landed
        correctIndex = shuffled.FindIndex(c => c == correctText);

        return shuffled;
    }
}